name: Sergey Karayev
author: Sergey Karayev
url: https://sergeykarayev.com
permalink: /:title
ordered_categories: [Academic Projects, Other Projects]
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "default"
